name: pr-checks

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    # This build will run in a roborio docker container that provided by wpilib.
    # Versions can be seen in:
    # https://hub.docker.com/r/wpilib/roborio-cross-ubuntu/tags
    container: wpilib/roborio-cross-ubuntu:2023-22.04

    # Give Permissions
    permissions:
      contents: read
      actions: write

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Verify that the java code compiles.
        run: ./gradlew --console=verbose build

  # This can be checked locally with either:
  #   ./gradlew :spotlessCheck
  #   ./gradlew :spotlessApply
  spotless:
    runs-on: ubuntu-latest

    # This build will run in a roborio docker container that provided by wpilib.
    # Versions can be seen in:
    # https://hub.docker.com/r/wpilib/roborio-cross-ubuntu/tags
    container: wpilib/roborio-cross-ubuntu:2023-22.04

    # Give Permissions
    permissions:
      contents: read
      actions: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      
      - run: ./gradlew spotlessCheck
